<!-- 
  POM Raiz del proyecto ws-javaexamples.
  - Define la versión del modelo POM (4.0.0).
  - Configura el groupId (es.udc.ws) y el artifactId (ws-javaexamples).
  - Incluye los submódulos: ws-jdbctutorial, ws-util y ws-movies.
  - Gestiona propiedades globales (codificación UTF-8, Java 25, versiones de dependencias).
  - Gestiona el plugin de ejecución SQL (MySQL) y el despliegue con Jetty/WAR.
-->

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>es.udc.ws</groupId>
        <artifactId>ws-javaexamples</artifactId>
        <version>3.10.0</version>
    </parent>
    <artifactId>ws-jdbctutorial</artifactId>
    <packaging>jar</packaging>
    <name>WS-JavaExamples JdbcTutorial Subsystem</name>

    <dependencies>
        <!-- JDBC driver -->
        <dependency>
            <groupId>${jdbcDriver.groupId}</groupId>
            <artifactId>${jdbcDriver.artifactId}</artifactId>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

</project>
